{% set name = "faker" %}
{% set version = "12.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Faker-{{ version }}.tar.gz
  sha256: aa7103805ae793277abbb85da9f6f05e76a1a295a9384a8e17c2fba2b3a690cb

build:
  number: 0
  noarch: python
  entry_points:
    - faker=faker.cli:execute_from_command_line
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-dateutil >=2.4
    - text-unidecode ==1.3
    - typing-extensions >=3.10.0.2

test:
  imports:
    - faker
    - faker.contrib
  commands:
    - pip check
    - faker --help
  requires:
    - pip

about:
  home: https://faker.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Faker is a Python package that generates fake data for you
  dev_url: https://github.com/joke2k/faker
  doc_url: https://faker.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
