{% set name = "Faker" %}
{% set version = "0.8.11" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "0857a92773c9cc6356c4c0c2aaa6f6ec83be94fc14fc0fd9e31904498d6fd388" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}


build:
  noarch: python
  entry_points:
    - faker = faker.cli:execute_from_command_line

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-dateutil >=2.4
    - six
    - ipaddress  # [py27]
    - text-unidecode

test:
  files:
    - run_test.py
  commands:
    - faker --help  # [osx]
    - PYTHONIOENCODING=utf8 faker --help  # [linux]
    - SET "PYTHONIOENCODING=utf8" & faker --help  # [win]
  requires:
    - email_validator >=1.0.0,<1.1.0
    - ukpostcodeparser >=1.1.1
    - mock

about:
  home: https://faker.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Faker is a Python package that generates fake data for you.'
  dev_url: https://github.com/joke2k/faker
  doc_url: https://faker.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
