{% set name = "faker" %}
{% set version = "30.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8760fbb34564fbb2f394345eef24aec5b8f6506b6cfcefe8195ed66dd1032bdb

build:
  entry_points:
    - faker=faker.cli:execute_from_command_line
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - typing_extensions
    - typing-extensions
    - python >=3.8
    - python-dateutil >=2.4

test:
  imports:
    - faker
  commands:
    - pip check
    - faker --help
  requires:
    - pip

about:
  home: https://faker.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Faker is a Python package that generates fake data for you
  dev_url: https://github.com/joke2k/faker
  doc_url: https://faker.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
