{% set version = "9.5.1" %}

package:
  name: faker
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/F/Faker/Faker-{{ version }}.tar.gz
  sha256: 46c854dbb3fab592dd1de97445ddd4408ab28e80a35962fe5392e87be13c9ee3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - faker = faker.cli:execute_from_command_line

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - python-dateutil >=2.4
    - text-unidecode ==1.3

test:
  requires:
    - pip
  files:
    - run_test.py
  commands:
    - pip check
    - PYTHONIOENCODING=utf8 faker --help  # [not win]
    - SET "PYTHONIOENCODING=utf8" & faker --help  # [win]
about:
  home: https://faker.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Faker is a Python package that generates fake data for you
  dev_url: https://github.com/joke2k/faker
  doc_url: https://faker.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
